### ISSUE TITLE
Re-sizing the jpopupmenu 

### ISSUE THREAD

**Issue by priyath** [eugener/oxbow#44]
The jpopupmenu that appears on a column header right click does not re-size properly. The problem appears to be with the menu.setPopupSize(newDim) method called inside the mouseDragged() listener method. This causes the mouseDragged() method to execute only once, and not repeatedly which it should, if it is to re-size the menu on a click and drag. I have described the problem in detail here.

http://stackoverflow.com/questions/34478414/resize-jpopupmenu-using-mouse-adapter

**Comment by eugener** [comment]
I've updated the code according to the discussion on `stackoverflow`. Both, the old and the new variants work on my Mac. Please test and let me know. 
Also, the best way to suggest a change is to simply send a pull request :)

**Comment by priyath** [comment]
Hey thanks for the prompt response, The stackoverflow suggestion does not work. The ancestor window returned by menu.getTopLevelAncestor() is of the jtable. Attempts to drag and resize the popupmenu changes the dimensions of the entire jtable in my case. I still have not found a fix for this. A possible reason is addressed by MadProgrammer in my stackoverflow post.

This is for the old variant:

"A call to setPopupSize, calls showPopup, this will close the current popup (if one is visible) and recreates the window based the new preferredSize of  "the popup. How the window is actually created is dependent on a number of system critieria. the MouseListeners remain intact, but, because the window is made visible, the mouse events are no longer been sent to it, but to the window beneath it, and, well, the whole thing explodes in flames.

**Comment by priyath** [comment]
```java
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;




 
public class TableExample extends JFrame
{
	private JPanel topPanel;
    private JPanel btnPanel;
    
    public TableExample() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException
    {
    	UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        //headers for the table
        String[] columns = new String[] {
            "Id", "Name", "Hourly Rate", "Part Time"
        };
         
        //actual data for the table in a 2d array
        Object[][] data = new Object[][] {
            {1, "John", 40.0, false },
            {2, "Rambo", 70.0, false },
            {3, "Zorro", 60.0, true },
        };
        
        topPanel = new JPanel();
        btnPanel = new JPanel();
        
        add(topPanel, BorderLayout.CENTER);
        add(btnPanel, BorderLayout.SOUTH);
        
       //create table with data
        JTable table = new JTable(data, columns);
        TableRowFilterSupport.forTable(table).searchable(true).apply();
        JButton button = new JButton();
         button.setText("save");
        //add the table to the frame
        topPanel.add(new JScrollPane(table));
        btnPanel.add(button);
        this.setTitle("Table Example");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       
        this.pack();
        this.setVisible(true);
        
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae){

            	table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            	table.getColumnModel().getColumn(0).setPreferredWidth(15);
            	table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            }

           });
    }
     
    public static void main(String[] args)
    {
    	
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
					new TableExample();
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InstantiationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IllegalAccessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (UnsupportedLookAndFeelException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }   
}

```

**Comment by eugener** [comment]
Does the `TableFilterTest` example produces the same issue?

**Comment by priyath** [comment]
Yes

**Comment by eugener** [comment]
Which Java version are you running under? Under my `1.8.0_65` I see no issue at all anymore.

**Comment by eugener** [comment]
Your example also works

**Comment by priyath** [comment]
Well look at that! I was running java 1.8.0_25 (x64), updated to 1.8.0_66 (x64) and the issue is no longer there. Both the old and new variants work fine. Thank you for the quick responses and apologies for any inconveniences caused.

**Comment by eugener** [comment]
Glad to hear that! Last commit actually makes the resizing smoother, so thank you for making me look into the issue :)

**Comment by priyath** [comment]
There is a problem with the latest commit, Re-sizing works fine if part of the popupmenu is outside of the table. But if the popupmenu is entirely inside the table, `menu.getTopLevelAncestor()` returns the window of the jtable which causes the table to resize and not the jpopupmenu.

**Comment by eugener** [comment]
Just tested and don't see any issues :)

**Comment by priyath** [comment]
Try maximizing the `TableFilterTest` table and re-sizing the jpopupmenu? 

My code is as below.
```
...
if ( newDim.width >= minDim.width && newDim.height >= minDim.height) {
			//menu.setPopupSize(newDim);
			resizeMenu(newDim);
        }

    }

    private void resizeMenu(Dimension dim) {
        final Window window = (Window) menu.getTopLevelAncestor();
//        window.pack();
        window.setSize(dim);
//        window.validate();
    }
```

**Comment by priyath** [comment]
The old variant `menu.setPopupSize(newDim)` works fine. Windows 8, jdk 1.8.0_66

**Comment by eugener** [comment]
Pretty strange... both work well no my machine with OSX

**Comment by eugener** [comment]
Updated the code to use resizing method based on OS
