### ISSUE TITLE
TableRowFilterSupport only sorting not filtering?

### ISSUE THREAD

**Issue by ddaneels** [eugener/oxbow#46]
Hello, 

I have the following java code. I wanted to add column filters, so I've added the TableRowFilterSupport.forTable to my code. 

However when clicking on a column header, I'm now able to sort the values in the column, but I don't see a possibility to filter. What is wrong?

private void updateTable() {

```
Object[] header = data.getHeaderForTable();
Object[][] content = data.getContentForTable();

jTable1 = new JTable(content, header);
TableRowFilterSupport.forTable(jTable1).apply();

jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
jTable1.setRowSelectionAllowed(true);
jTable1.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        classifyMenu.setEnabled(true);
    }
});

jScrollPane2.setViewportView(jTable1);
repaint();
```

}

**Comment by DanhDue** [comment]
I have the same problem.
Do you find the approach to solving it?

**Comment by eugener** [comment]
Have you tried to right-click on the column header? :)

**Comment by DanhDue** [comment]
Oh my god!
Many Thanks!
=)))))))
