### ISSUE TITLE
No compatibility with latest miglayout version

### ISSUE THREAD

**Issue by Bios-Marcel** [eugener/oxbow#52]
When using the latest version of miglayout, the choice dialog buttons are huge:

![b8aaaabda12a471698676efdfe8de871](https://cloud.githubusercontent.com/assets/19377618/24664643/7c82d438-195b-11e7-9e7d-c4d514f6457f.png)
![bug2](https://cloud.githubusercontent.com/assets/19377618/24664647/7dad1008-195b-11e7-9b47-203852baa3a4.png)

No manual adjustments were made. We have just updated the miglayout library from 3.7.4 to 5.0.

**Comment by eugener** [comment]
Unfortunately, I currently don't have time to address issues in Oxbow project, but I would welcome a pull request if you can come up with the fix.

**Comment by Bios-Marcel** [comment]
@eugener I have created a pull request.
