### ISSUE TITLE
When is next release?

### ISSUE THREAD

**Issue by bpridemore** [eugener/oxbow#63]
There’s only one release, should I just clone and build jars from the project clone? I want some of the new features specifically the custom cell rendering.

**Comment by PureSpider** [comment]
Wondering this, too! I am using miglayout in my project and the dependency on the old miglayout "all in one" version breaks my project currently.

**Comment by eugener** [comment]
Unfortunately this project is on the back burner due to lack of time.
@PureSpider I think you can exclude the older dependency in favor of new one.

**Comment by PureSpider** [comment]
Good call, I'll try that!
