### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by Bios-Marcel** [eugener/oxbow#66]
Hello,

i have noticed, that this project doesn't have any license, meaning that by default, the original author / owner should have the copyright and retain all rights. However, I believe this originally wasn't your project, but a project by a company or individual called `EzWare`. The version by EzWare, was licensed with the BSD License, meaning that this repository should theoretically have at least a BSD-License or a BSD-Compatible License. However, I have checked the previous revisions of this repository and wasn't able to find any license.

Could you provide any information on this projects history? Have you manually removed the license? Did you take over the project officially, meaning that you are the owner now?

Regards
Marcel

**Comment by eugener** [comment]
Hello Marcel,

This project was started and developed by me. ezware.com domain still belongs to me and my partner (as well as the company in US). The intention was always to develop it under BSD license. 
So if someone is still interested in it, the license can be added/updated.

**Comment by Bios-Marcel** [comment]
Hey,

thanks for the quick reply. It'd be great if you could add the license to the repo again, as this is quite interesting for people shipping software that uses this library, which is in my case what we are doing.

**Comment by eugener** [comment]
Here we go. Added the license file.

**Comment by Bios-Marcel** [comment]
Thank you :)
